/**
 * Demo mode — instant, zero-upload sample reports.
 *
 * The JSON in `public/demo/` is REAL output from the production analyzers,
 * generated by `scripts/generate_demo_reports.py` against the sample videos.
 * It is not mocked or hand-written: same scores, same metrics, same annotated
 * frames a live upload produces.
 *
 * Why this exists: a live analysis is CPU-bound and takes minutes on free-tier
 * hardware, and the container may be cold. A visitor evaluating the project
 * will not wait that long. Demo mode gives them the full report in one click,
 * served straight from the CDN with the API never touched.
 */
import type { AssessmentType } from '@/data/registry';

export interface DemoIndexEntry {
  assessmentType: AssessmentType;
  slug: string;
  score: number;
  status: string;
  summary: string;
  annotatedFrames: number;
  file: string;
  bytes: number;
}

export interface DemoIndex {
  generated: string;
  reports: DemoIndexEntry[];
}

/** Vite serves `public/` from the site root, so these are absolute paths. */
const DEMO_BASE = '/demo';

let indexCache: DemoIndex | null = null;
const reportCache = new Map<string, any>();

/** Load the lightweight catalogue of available sample reports (~4 KB). */
export async function loadDemoIndex(): Promise<DemoIndex> {
  if (indexCache) return indexCache;
  const res = await fetch(`${DEMO_BASE}/index.json`, { cache: 'force-cache' });
  if (!res.ok) throw new Error(`Demo index unavailable (HTTP ${res.status})`);
  indexCache = (await res.json()) as DemoIndex;
  return indexCache;
}

/**
 * Load one full sample report. These are large (0.1–3.8 MB) because they carry
 * base64 annotated frames, so they are fetched lazily — one at a time, only
 * when the user actually opens that exercise — and memoised per session.
 */
export async function loadDemoReport(
  type: AssessmentType,
  slug: string,
): Promise<any> {
  const key = `${type}__${slug}`;
  const cached = reportCache.get(key);
  if (cached) return cached;

  const res = await fetch(`${DEMO_BASE}/${key}.json`, { cache: 'force-cache' });
  if (!res.ok) throw new Error(`No sample report for ${type}/${slug}`);
  const result = await res.json();

  // Tag it so the UI can be honest about what the viewer is looking at.
  result._isDemo = true;
  reportCache.set(key, result);
  return result;
}

/** The report to open when the user clicks "See a sample report". */
export const FLAGSHIP_DEMO: { type: AssessmentType; slug: string } = {
  type: 'mobility',
  slug: 'knee-to-wall-test',
};

const DEMO_FLAG_KEY = 'mobilityai_demo_mode';

export function isDemoMode(): boolean {
  try { return localStorage.getItem(DEMO_FLAG_KEY) === '1'; } catch { return false; }
}

export function setDemoMode(on: boolean): void {
  try {
    if (on) localStorage.setItem(DEMO_FLAG_KEY, '1');
    else localStorage.removeItem(DEMO_FLAG_KEY);
  } catch { /* private browsing — demo still works, just not remembered */ }
}
